Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".vagrant/"]

  config.vm.define "achraitiS" do |server|
    server.vm.hostname = "achraitiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  config.vm.define "achraitiSW" do |worker|
    worker.vm.hostname = "achraitiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/install_k3s_agent.sh"
  end
end
